### ISSUE TITLE
Not able to use colorpicker-hue to select 1st color on blank color picker 

### ISSUE THREAD

**Issue by nageshkdeshmane** [farbelous/bootstrap-colorpicker#242] opened 2017-11-28 09:01 UTC
### Description

I have text-box with color-picker same as 1st example in examples https://farbelous.github.io/bootstrap-colorpicker/tutorial-01_Basics.html

When I click on it color picker comes but when I click on colorpicker-hue to select green color, it by default always select red and shows red saturation. Unless and until, we select something on red, it doesn't allow to select any other color.

### Context

- bootstrap-colorpicker version: v3.0.0
- bootstrap version: v3.3.4
- jQuery version: v3.2.1
- Browser name and version: Chrome, actually all browsers
- Operative System name an version: Windows 10

### Expected behavior

When I click on green color in colorpicker hue, it should show green in colorpicker saturation instead of red.

### Actual behavior

When there is no color selected yet, and I open color picker and click on colorpicker hue, it should show selected color in the colorpicker saturation.

### Live Example
First example in examples link.
https://farbelous.github.io/bootstrap-colorpicker/tutorial-01_Basics.html
Same also happens on this jsfiddle.net http://jsfiddle.net/0vopxm13/157/

**Comment by itsjavi** [comment] 2017-12-04 10:35
Thanks for your report, but this is a duplicate of https://github.com/farbelous/bootstrap-colorpicker/issues/203

**Closed by itsjavi** 2017-12-04 10:35 UTC
