### ISSUE TITLE
Moving to the left of saturation disables hue

### ISSUE THREAD

**Issue by AlexanderKheimonen** [farbelous/bootstrap-colorpicker#230] opened 2017-10-08 14:08 UTC
Can be reproduced on all examples except 'background color' one: https://farbelous.github.io/bootstrap-colorpicker/

1. Open colorPicker.
2. Move dot selector on saturation panel to its left side.
Saturation panel switches to red-black. Hue is irresponsive.

Why this is happening on all colorPicker examples except 'background'? What is the difference? :)

**Comment by itsjavi** [comment] 2017-11-07 15:26
Duplicate of https://github.com/farbelous/bootstrap-colorpicker/issues/203
please search for existing issues before creating duplicated ones. thanks.

**Closed by itsjavi** 2017-11-07 15:26 UTC
Labels: duplicate
