### ISSUE TITLE
Sliders not usable when color is black/white/gray/transparent

### ISSUE THREAD

**Issue by alexandervlpl** [farbelous/bootstrap-colorpicker#203] opened 2017-02-10 18:11 UTC
When the initial (or user-selected) colour is black, white or grey the vertical colour slider does not work. It shows no current position, and clicking or dragging on it has no effect.

This can be reproduced on the home page by entering "#000000" or "#FFFFFF" into one of the example fields:
https://itsjavi.com/bootstrap-colorpicker/

![colorpicker-bug](https://cloud.githubusercontent.com/assets/8945883/22838226/49a5c0f2-efd5-11e6-958f-4b673b1480f9.png)

**Comment by mike42** [comment] 2017-03-19 11:08
I can reproduce this bug in both Firefox and Chrome on the documentation page.

**Comment by desirade-fm** [comment] 2017-06-08 15:12
I have the same problem. 
When I'm selecting black or white color, the HUE is always setting to max (100 by default). 
In documentation page I don't have this problem on "Working with events" and "Inline mode" examples.

**Comment by itsjavi** [comment] 2017-09-24 22:22
It is not a bug, it is how it should work.

When white and black have no hue, so it makes sense that moving the hue bar has no effect, unless you move the saturation. That's how colors work ;)

**Comment by alexandervlpl** [comment] 2017-10-26 07:59
I realize black and white have no hue. In other colour pickers, that bar still changes the hue of the main palette (the largest square in the picker), even when your selected colour is black or white. This makes it easy to and untuitive to change from white to blue, for example.

Right now it's very unintuitive. If white is selected, it's not obvious how to change the colour to blue. People don't realize you have to click in the large square to enable the hue slider. They just click on the slider and nothing happens.

I think the slider should work the way users expect it to. Or at least it should be visibly disabled when it's not usable.

**Comment by itsjavi** [comment] 2017-10-26 22:47
I get your point now.
I guess like everyone I'm busy, so note that pull requests will get merged quicker than feature requests are implemented.

**Comment by mtilokani** [comment] 2017-10-30 05:29
Hi, I am facing similar problem, is there any solution for this ?

**Comment by itsjavi** [comment] 2017-11-07 15:26
@mtilokani for now the only solution is someone proposing a change and sending a pull request ;)

**Comment by 1dd0** [comment] 2017-12-06 21:34
It happens because it creates Color instance from input value.
`this.color = this.createColor(this.input.val());`
"Working with events" and "Inline mode" examples works as expected because they haven't input and logic shown above doesn't use.

**Comment by 1dd0** [comment] 2017-12-06 21:40
Just remove input with color value.
It solves few artifacts related with unexpected hue changing.
If you need to show color value you can set it using events.

**Comment by antag0n1st** [comment] 2017-12-14 17:59
I added this:
`if(this.color.value.s === 0){
              this.color.setSaturation(0.2);
          }`

right after (line 1152):
`this.currentSlider = $.extend({}, sl.hue)`

**Comment by cupcakedream** [comment] 2018-02-19 14:40
This is a usability nightmare - went with another plugin because of this major bug

**Comment by itsjavi** [comment] 2018-02-20 11:33
@cupcakedream thanks for your contribution. If you have a solution please let us know

**Comment by itsjavi** [comment] 2018-02-20 11:34
@antag0n1st thanks but that looks more like a quick hack than a durable solution :(

**Comment by BrainFeeder** [comment] 2018-03-23 13:24
@cupcakedream Can you share the URL to the other plugin? This one seemed to work fine untill I kept hitting usability problems. I'm not even getting the alpha slider to work properly :| 
I would report this as a bug, but maintainers are too busy to maintain, so ...

**Comment by cupcakedream** [comment] 2018-03-23 13:55
Sure it's http://huebee.buzz/ - It's simpler but gets the job done.

**Comment by emrldwpn** [comment] 2018-03-23 23:49
This bug is actually much worse than described.  It occurs whenever the red, green, and blue values are the same.  So not just white, black, and gray, but also anything like #666666, #e0e0e0, etc.  Since these are fairly common color codes, and it's very unclear to the user what's going on, I'm not really sure how people are using this plugin in production.

Expanding upon what @antag0n1st posted above, I hacked this up.  It's far from elegant but definitely better than using the plugin as is.

`else if (zone.is('.colorpicker-hue')) {
            var val = this.getValue();
            val = (val === null || val === undefined) ? "" : val.toUpperCase();
            if (val === "#000000")
            {
                this.setValue("#000001");
            }
            else if (val === "#FFFFFF")
            {
                this.color.setSaturation(0.01);
            }
            else
            {
                if (val.length === 7)
                {
                    val = val.substring(1);
                }
                if (val.length === 6)
                {
                    var r = val.substring(0, 2);
                    var g = val.substring(2, 4);
                    var b = val.substring(4, 6);
                    if (r === g && g === b)
                    {
                        this.color.setSaturation(0.5);
                    }
                }
            }
            this.currentSlider = _jquery2.default.extend({}, sl.hue);
        }`

**Comment by BrainFeeder** [comment] 2018-03-23 23:58
@emrldwpn Can you describe where to put the hacked up code :)
I'm also trying to get this picker to pop UP, when the input is at the bottom of a viewport. Any ideas?
The last version I used in an older project did not have all these bugs...

**Comment by emrldwpn** [comment] 2018-03-24 00:06
Sure @BrainFeeder.  Going off the latest version of the code, in [bootstrap-colorpicker.js](https://github.com/farbelous/bootstrap-colorpicker/blob/master/dist/js/bootstrap-colorpicker.js#L1563) you'll see starting at line 1563:
`      if (!zone.is('.colorpicker')) {
        if (zone.is('.colorpicker-saturation')) {
          this.currentSlider = _jquery2.default.extend({}, sl.saturation);
        } else if (zone.is('.colorpicker-hue')) {
          this.currentSlider = _jquery2.default.extend({}, sl.hue);
        } else if (zone.is('.colorpicker-alpha')) {
          this.currentSlider = _jquery2.default.extend({}, sl.alpha);
        } else {
          return false;
        }`

You can replace this portion of that code:
`else if (zone.is('.colorpicker-hue')) { this.currentSlider = _jquery2.default.extend({}, sl.hue); }`

with my code above.  It's currently located at lines 1566 & 1567.

**Comment by BrainFeeder** [comment] 2018-03-24 00:20
Thanks @emrldwpn I'll try it. I am using the minified file though ..

Adding the following CSS will add the 'transparant' image background to the selected color in the swatch.
Users will then see if an alpha channel is selected on the colorpicker, without having to open it first.

    .colorpicker-component .input-group-addon em {
        background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAABkCAQAAAAVxWkcAAABr0lEQVR4Xo2VwU0DQQxF7dmRuNIFlzlSAR3QAaXQQdIBJVABFXDcOVAAd67cjJLR07dkhcSrkZKfb/t7bG88rFo3B5gZPMNycItu2xloGV7MWHzM9zuzFWCkmA0nK6AszCUJDW6+mG6R03ncw5v8EMTEvZ2O3AliYjpslblc0RF9LmZYWxURU6aKytWZYsoWCAe+xwOZp1GsEukGiIkYxcQCHck99+gRgB7JncyIB5SGEhP3Yh5P6JwX+u6AnYot104d8DJT7uH7M9JH6OZbimj0vfMVaYnJIZFJDBW9kHlerL2C6JV4mSt7uuo2N57RxnZ+usQjn0R1jwBJBrNO3evJpVYUWsJ/E3UiXRlv24/7YZ04xmEdWlzcKS+B/eapeyMvFd2k0+hRk/T0AmTW8h69s2sjYMsdPntECiILhAeIMZAeH4QvUwfn6ijC0tTV+fT9ky8jM9nK2g7Ly1VjSpKYq6IvsAm7MtNu1orEqa/K3KNvgMFdhfquPfJmp2dbh0/8Gzb6Y22ViaNr6n5410zXdngVhbu6XqdOtWOuin5hjABGp4a2uotZ71MVCfwDBt2/v37yo6AAAAAASUVORK5CYII=);
        background-position: 0 100%;
        height:16px;
    }
    .colorpicker-component .input-group-addon i {
        margin-top:-2px;
    }

In the HTML I simply wrapped the `<i></i>` with `<em></em>`.

(I'm using Bootstrap 4, for other versions adding this styling might be a bit different.)

**Comment by BlueRaja** [comment] 2018-05-09 12:42
Is this project abandoned?  This is a deal-breaker bug, and makes this project completely unusable for production use.

**Comment by itsjavi** [comment] 2018-05-09 21:53
@BlueRaja why abandoned? it's not abandoned but it is mainly maintained by me and I have no much time.
if someone has time and ideas about how to fix this, please send a PR ;)

**Comment by alex-kowalski** [comment] 2018-06-06 00:26
Hello
I have faced the same problem.
This is good color picker, but this bug is really not good.
How is it going?

**Comment by itsjavi** [comment] 2018-07-21 17:11
Thanks to @sergeir82 this bug has been fixed on v2.5.3 (released today).

I am going to prepare a fix for the master/v3.0 version

**Comment by cupcakedream** [comment] 2018-07-21 17:49
Hooray!

**Comment by alex-kowalski** [comment] 2018-07-22 20:31
@itsjavi , It works. Thanks

**Closed** 2018-07-25 17:22 UTC
Labels: bug, help wanted

**Comment by jmgarza** [comment] 2018-11-02 14:40
I had trouble finding the 2.5.3 release files.
So here it is for anyone that's also looking for it: [2.5.3](https://github.com/farbelous/bootstrap-colorpicker/archive/2.5.3.zip)
